### ISSUE TITLE
fiber/setmaxstack may not work

### ISSUE THREAD

**Issue by jkleiser** [janet-lang/janet-lang.org#13]
I tried `(fiber/setmaxstack (fiber/current) 16384)`, both in a script and in the REPL, but when I do `(fiber/maxstack (fiber/current))` afterwards, I still get 8192.
I'm using an up to date Janet 0.4.0-4713219 on macOS 10.14.3.

**Comment by bakpakin** [comment]
In the repl and in scripts, Janet currently spawns a new fiber for each top level form. This is because Janet uses incremental compilation, and evaluates top level forms before compiling the next form. I suppose I could rework the run-context function in core.janet to reuse the fiber unless an error occurred.

**Comment by bakpakin** [comment]
I didn't realize when I replied, but please open issues about the Janet language in the [Janet](https://github.com/janet-lang/janet) repository - this repo is for the website.
