### ISSUE TITLE
Multithreading section still refers to `thread/` functions despite deprecation

### ISSUE THREAD

**Issue by EleanorNB** [janet-lang/janet-lang.org#130]
Section should be updated with the proper way to do multithreading now.

**Comment by sogaiu** [comment]
In the mean time, I've assembled / remixed a document regarding recent developments: [Threading in Janet using ev](https://gist.github.com/sogaiu/405af60cc10c0c1d13c26bf2a84b05bf).

**Comment by uvtc** [comment]
Is the issue here that the current chapter on threads (multithreading) should use functions from `ev`?

If that's the case, another option may be to create a "concurrency and parallelism" directory that contains chapters on:

  * fibers (which has its *own* subdir docs)
  * event loop
  * threads

(I think I remember seeing @bakpakin write in the chat that if the function name has "thread" anywhere in it, then it's talking about actual threads (that map to native threads). Correct?)

An intro chapter in such a top-level "concurrency-and-parallelism/index.mdz" doc would be an excellent place to make some things clear from the get-go --- my understanding of these things so far is:

  * fibers: for concurrency ("time-sliced"). "Scheduling" is done cooperatively (via `yield` and `resume`).
  * threads: for parallelism (if multiple CPUs are available). Scheduling is done preemptively (by the OS). Threads in your program map directly to native (aka kernel) threads.

**Comment by uvtc** [comment]
@sogaiu , in your [Threading in Janet using ev](https://gist.github.com/sogaiu/405af60cc10c0c1d13c26bf2a84b05bf) doc, you write:

> "Threads in Janet do not share a memory heap and must communicate via message passing using a thread channel."

My understanding is that all threads share the process's address space and resources... they all have access to the program's globals, correct? Maybe I'm confusing those things with the memory heap you mention in your doc?

**Comment by sogaiu** [comment]
> Is the issue here that the current chapter on threads (multithreading) should use functions from `ev`?

In case it wasn't clear, the thread module was deprecated with the 1.17.0 release -- see the third item from the top of the [CHANGELOG.md file](https://github.com/janet-lang/janet/blob/master/CHANGELOG.md#1170---2021-08-21).

If one wants to use thread stuff in Janet going forward, then I believe the thread support in ev is the recommended built-in path.

So it seems like the current page on multithreading continuing to exist in its current form doesn't communicate that message.

**Comment by sogaiu** [comment]
FWIW, the text I linked to is basically a rearrangement of existing material that was written by others (I think mostly bakpakin).

As I understand it "Threads in Janet" make use of (but are not the same thing as) underlying operating system thread primitives, e.g. pthreads on unixen or if on Windows whatever is used by Janet there.  "Threads in Janet" are an abstraction on top of those things -- we don't get access to everything they can do (for good reasons IIUC).

**Comment by EleanorNB** [comment]
The section has now been rewritten and this problem has been fixed.
