### ISSUE TITLE
HTTP Status 403 for `assets/favicon.ico:1`

### ISSUE THREAD

**Issue by icp1994** [janet-lang/janet-lang.org#150]
...on `/docs`, `/api` and `/capi` pages

**Comment by sogaiu** [comment]
I get similar results.

I tried the changing:

* https://github.com/janet-lang/janet-lang.org/blob/9bcc5d4b6a603c72feb15ce6871be0cbb5978fa8/templates/docpage.html#L11
* https://github.com/janet-lang/janet-lang.org/blob/9bcc5d4b6a603c72feb15ce6871be0cbb5978fa8/templates/index.html#L11

to use `../assets` instead of `assets` and that seemed to help.

**Comment by sogaiu** [comment]
I no longer get 403s.  May be #160 was enough to address this.

@icp1994 May be this issue can be closed now?

**Comment by icp1994** [comment]
Sure, looks fixed to me.
